name: AnniSim
version: 1.0
main: me.munir.annisim.AnniSimPlugin
api-version: '1.21'

commands:
  startgame:
    description: Starts the game on the selected map
    usage: /startgame <map>
  endgame:
    description: Ends the game
  mute:
    description: Mutes or unmutes a player
    usage: /mute <player>
