package me.munir.annisim;

import java.util.Objects;
import me.munir.annisim.arena.ArenaManager;
import me.munir.annisim.chat.ChatMuteManager;
import me.munir.annisim.command.EndGameCommand;
import me.munir.annisim.command.BanLoadoutCommand;
import me.munir.annisim.command.CommandProtectionManager;
import me.munir.annisim.command.LoadoutTabCompleter;
import me.munir.annisim.command.MuteCommand;
import me.munir.annisim.command.ProtectCommand;
import me.munir.annisim.command.ResetCommand;
import me.munir.annisim.command.StartGameCommand;
import me.munir.annisim.command.StartGameTabCompleter;
import me.munir.annisim.command.UnbanLoadoutCommand;
import me.munir.annisim.game.GameManager;
import me.munir.annisim.game.RoundItems;
import me.munir.annisim.game.WinTracker;
import me.munir.annisim.kit.KitManager;
import me.munir.annisim.kit.SuccubusManager;
import me.munir.annisim.listener.ArenaMobSpawnListener;
import me.munir.annisim.listener.AcrobatListener;
import me.munir.annisim.listener.BlinkListener;
import me.munir.annisim.listener.DasherItemListener;
import me.munir.annisim.listener.DiamondBlockProtectionListener;
import me.munir.annisim.listener.DiamondListener;
import me.munir.annisim.listener.GameDeathListener;
import me.munir.annisim.listener.GameWinListener;
import me.munir.annisim.listener.GodAppleConsumeListener;
import me.munir.annisim.listener.IronArmorDurabilityListener;
import me.munir.annisim.listener.KitSelectorListener;
import me.munir.annisim.listener.LaunchPadListener;
import me.munir.annisim.listener.LoadoutSelectorListener;
import me.munir.annisim.listener.LobbyItemProtectionListener;
import me.munir.annisim.listener.LobbyJoinListener;
import me.munir.annisim.listener.LobbyProtectionListener;
import me.munir.annisim.listener.LobbyRespawnListener;
import me.munir.annisim.listener.SuccubusListener;
import me.munir.annisim.listener.TeamChatListener;
import me.munir.annisim.listener.TeamDamageListener;
import me.munir.annisim.listener.TeamQuitListener;
import me.munir.annisim.listener.TeamSelectorListener;
import me.munir.annisim.loadout.LoadoutManager;
import me.munir.annisim.lobby.LobbyItems;
import me.munir.annisim.lobby.LobbyManager;
import me.munir.annisim.scoreboard.ScoreboardManager;
import me.munir.annisim.team.TeamManager;
import org.bukkit.command.PluginCommand;
import org.bukkit.plugin.java.JavaPlugin;

public class AnniSimPlugin extends JavaPlugin {
   public void onEnable() {
      this.saveDefaultConfig();
      LobbyManager lobbyManager = new LobbyManager(this);
      ArenaManager arenaManager = new ArenaManager(this);
      LobbyItems lobbyItems = new LobbyItems(this);
      RoundItems roundItems = new RoundItems(this);
      TeamManager teamManager = new TeamManager();
      ChatMuteManager chatMuteManager = new ChatMuteManager();
      CommandProtectionManager commandProtectionManager = new CommandProtectionManager();
      KitManager kitManager = new KitManager();
      LoadoutManager loadoutManager = new LoadoutManager(this, roundItems);
      WinTracker winTracker = new WinTracker(this);
      GameManager gameManager = new GameManager(this, lobbyManager, arenaManager, lobbyItems, roundItems, kitManager, teamManager, loadoutManager, winTracker);
      SuccubusManager succubusManager = new SuccubusManager(gameManager, teamManager, kitManager, roundItems);
      ScoreboardManager scoreboardManager = new ScoreboardManager(this, gameManager, teamManager, succubusManager, winTracker);
      DiamondListener diamondListener = new DiamondListener(this, gameManager, arenaManager, teamManager);
      gameManager.setScoreboardManager(scoreboardManager);
      gameManager.setDiamondListener(diamondListener);
      lobbyManager.loadLobbyWorld();
      arenaManager.loadArenaWorld();
      this.getServer().getPluginManager().registerEvents(new LobbyJoinListener(lobbyManager, lobbyItems), this);
      this.getServer().getPluginManager().registerEvents(new LobbyRespawnListener(lobbyManager, arenaManager, gameManager), this);
      this.getServer().getPluginManager().registerEvents(new LobbyProtectionListener(lobbyManager), this);
      this.getServer().getPluginManager().registerEvents(new LobbyItemProtectionListener(lobbyItems), this);
      this.getServer().getPluginManager().registerEvents(new LaunchPadListener(this), this);
      this.getServer().getPluginManager().registerEvents(new TeamSelectorListener(lobbyItems, gameManager, teamManager), this);
      this.getServer().getPluginManager().registerEvents(new TeamQuitListener(teamManager), this);
      this.getServer().getPluginManager().registerEvents(new KitSelectorListener(lobbyItems, kitManager), this);
      this.getServer().getPluginManager().registerEvents(new LoadoutSelectorListener(lobbyItems, gameManager, loadoutManager), this);
      this.getServer().getPluginManager().registerEvents(new GodAppleConsumeListener(this), this);
      this.getServer().getPluginManager().registerEvents(new IronArmorDurabilityListener(this), this);
      this.getServer().getPluginManager().registerEvents(new TeamDamageListener(gameManager, teamManager), this);
      this.getServer().getPluginManager().registerEvents(new DiamondBlockProtectionListener(), this);
      this.getServer().getPluginManager().registerEvents(new TeamChatListener(teamManager, chatMuteManager), this);
      this.getServer().getPluginManager().registerEvents(new AcrobatListener(this, gameManager, kitManager, teamManager), this);
      this.getServer().getPluginManager().registerEvents(new BlinkListener(this, gameManager, roundItems, kitManager), this);
      this.getServer().getPluginManager().registerEvents(new SuccubusListener(this, succubusManager), this);
      this.getServer().getPluginManager().registerEvents(new DasherItemListener(roundItems), this);
      this.getServer().getPluginManager().registerEvents(new ArenaMobSpawnListener(arenaManager, gameManager), this);
      this.getServer().getPluginManager().registerEvents(diamondListener, this);
      this.getServer().getPluginManager().registerEvents(new GameWinListener(this, gameManager), this);
      this.getServer().getPluginManager().registerEvents(new GameDeathListener(this, gameManager, kitManager, loadoutManager, teamManager), this);
      scoreboardManager.start();
      ((PluginCommand)Objects.requireNonNull(this.getCommand("startgame"))).setExecutor(new StartGameCommand(gameManager, arenaManager, commandProtectionManager));
      ((PluginCommand)Objects.requireNonNull(this.getCommand("startgame"))).setTabCompleter(new StartGameTabCompleter(arenaManager));
      ((PluginCommand)Objects.requireNonNull(this.getCommand("endgame"))).setExecutor(new EndGameCommand(gameManager));
      ((PluginCommand)Objects.requireNonNull(this.getCommand("mute"))).setExecutor(new MuteCommand(chatMuteManager));
      ((PluginCommand)Objects.requireNonNull(this.getCommand("reset"))).setExecutor(new ResetCommand(winTracker, commandProtectionManager));
      ((PluginCommand)Objects.requireNonNull(this.getCommand("ban"))).setExecutor(new BanLoadoutCommand(loadoutManager, gameManager, commandProtectionManager));
      ((PluginCommand)Objects.requireNonNull(this.getCommand("ban"))).setTabCompleter(new LoadoutTabCompleter());
      ((PluginCommand)Objects.requireNonNull(this.getCommand("unban"))).setExecutor(new UnbanLoadoutCommand(loadoutManager, commandProtectionManager));
      ((PluginCommand)Objects.requireNonNull(this.getCommand("unban"))).setTabCompleter(new LoadoutTabCompleter());
      ((PluginCommand)Objects.requireNonNull(this.getCommand("protect"))).setExecutor(new ProtectCommand(commandProtectionManager));
      this.getLogger().info("AnniSim plugin enabled!");
   }

   public void onDisable() {
      this.saveConfig();
      this.getLogger().info("AnniSim plugin disabled!");
   }
}
